### ISSUE TITLE
po amigo

### ISSUE THREAD

**Issue by linntwc** [oyuridev/Serenys-Api#1]
oi

**Comment by linntwc** [comment]
é isso q acontece quando o pai estupra o filho, cresce e fica assim....

**Comment by oyuridev** [comment]
oi

**Comment by Akiraaaaaaaaa** [comment]
Kkkkkk essa src é paga ele vazou pra noix

**Comment by linntwc** [comment]
realmente, vendi pra 20 pessoas e mandei pra umas 4 de graça, fiz a 4 meses, VAsoUU PRA cARalHo!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! quase gosei com esse vazamento, nao da pra esperar mto cérebro de qm é de web familia ainda mais de Lofy member.

**Comment by Akiraaaaaaaaa** [comment]
Kkkkkkkkkk

**Comment by Akiraaaaaaaaa** [comment]
Cuidado com que fala por aí viu

**Comment by i8v** [comment]
Cuidado com que fala por aí viu
